spring.application.name=ms-usuarios

# Puerto de ejecución del Microservicio Usuarios
server.port=8081

# Conexión a la base de datos de XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/bd_usuarios?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuración Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect